# These are supported funding model platforms

github: [mahisataruna] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: algorithmdev # Replace with a single Ko-fi username
buy_me_a_coffee: algorithmdev # Replace with a single Buy Me a Coffee username
thanks_dev: mahisataruna # Replace with a single thanks.dev username
